apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: myapp
spec:
  type: NodePort
  ports:
  - port: 8761
  selector:
    app: eureka-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-container
  namespace: myapp
  labels:
    app: eureka-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-app
  template:
    metadata:
      labels:
        app: eureka-app
    spec:
      containers:
      - name: eureka-container
        image: 580044464645.dkr.ecr.us-east-1.amazonaws.com/portfolio_eureka:2
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 8761
      imagePullSecrets:
          - name: regcred